[book]
authors = ["Markus Unkel <markus@unkel.io>"]
language = "en"
multilingual = false
src = "src"
title = "odesign Book"

[output.html]
mathjax-support = true

[output.html.playground]
editable = false
runnable = false
