[config]
default_to_workspace = false

[tasks.cov-cobertura]
command = "cargo"
args = [
    "llvm-cov",
    "report",
    "--lcov",
    "--output-path",
    "lcov.info"
]

[tasks.test]
command = "cargo"
args = [
  "nextest",
  "run"
]


[tasks.book-watch]
command = "mdbook"
args = [
  "watch",
  "odesign-book",
  "--open"
]

[tasks.book-build]
command = "mdbook"
args = [
  "build",
  "odesign-book",
]

[tasks.book-deploy-tar]
dependencies = ["book-build"]
script = "tar --exclude='./odesign-book/src/' -cvf ./deploy.tar ./captain-definition ./odesign-book/*"

[tasks.book-deploy]
script = "caprover deploy -t ./deploy.tar"
dependencies = ["book-deploy-tar"]
