[package]
name = "odesign"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[dependencies]
nalgebra = { workspace = true }
num-dual = { workspace = true }
faer = { workspace = true }
faer-ext = { workspace = true }
rayon = "1.10.0"
thiserror = { workspace = true }
aquamarine = { workspace = true }
katexit = { workspace = true }
odesign_derive = { path = "../odesign-derive"}

[dev-dependencies]
rand = "0.9.0"
trybuild = "1.0"
